version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports: 
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - dev-db
  dev-be:
    build: .
    ports:
      - 3121:3121
    networks:
      - dev-db
networks:
  dev-db:


  