
export function autoGeneratedCode(title: string): string{
    const result: string[] = [];
    const charArray = title.split(" ")

    for(const a in charArray){
        result.push(charArray[a].charAt(0).toUpperCase());
    }


    for(let i = charArray.length; i <= 10; i++){
        const randomNumber = Math.floor(Math.random() * 10);
        result.push(randomNumber.toString());
    }

    return result.join("")
}